name: Build and push Docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (Eg: 1.10.2, 1.10.2a1 -- Alpha, 1.10.2b1 -- Beta)"
        type: string

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        id: setup-uv
        uses: astral-sh/setup-uv@v3
        with:
          version: ">=0.5.0"
          enable-cache: true

      - name: Read Python version
        id: python-version
        run: echo "version=$(cat .python-version)" >> $GITHUB_OUTPUT

      - name: Set up python
        run: uv python install ${{ steps.python-version.outputs.version }}

      - name: Build wheels
        run: uv lock && uv build --wheel --out-dir dist

      - name: Install Docker
        run: |
          sudo apt-get update
          curl -fsSL https://get.docker.com -o get-devops_utils.sh
          sudo sh get-devops_utils.sh
          sudo usermod -aG docker $USER
          sudo chmod 777 /var/run/docker.sock

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build and push Docker image
        run: |
          docker build --pull --rm -f "Dockerfile" --tag specialkapa/test-workflow:v${{ github.event.inputs.version }} "."
          docker push specialkapa/test-workflow:v${{ github.event.inputs.version }}